version: "2.4"

networks:
  gesoft_net:
    name: gesoft_net
    driver: bridge

services:
  db:
    container_name: Mariadb
    image: mariadb
    restart: unless-stopped
    networks:
      - "gesoft_net"
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_DATABASE}
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
    tty: true
      
  app:
    container_name: appWeb
    image: rogerionasc/gesoft:latest
    restart: unless-stopped
    entrypoint: bash -c '/etc/init.d/apache2 start && php /var/www/html/appWeb/artisan serve --host 0.0.0.0'
    networks:
      - gesoft_net
    ports:
      - "8000:8000"
      - "8080:80"
    working_dir: /var/www/html/appWeb
    volumes:
      - ./appWeb:/var/www/html/appWeb
    depends_on:
      - db
    tty: true
